// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0DfVCh4ucYp4RMJO2vt6_0N_bTWc858A',
    appId: '1:977368093099:web:763927935e924042ec42ee',
    messagingSenderId: '977368093099',
    projectId: 'yesyes-82dcf',
    authDomain: 'yesyes-82dcf.firebaseapp.com',
    storageBucket: 'yesyes-82dcf.appspot.com',
    measurementId: 'G-74R4N83FD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPhYqsKvmqqf_rfHfrNQmkfN9CT0BMsf0',
    appId: '1:977368093099:android:31b4f5359eaa7b03ec42ee',
    messagingSenderId: '977368093099',
    projectId: 'yesyes-82dcf',
    storageBucket: 'yesyes-82dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwj3Rfnx3AV7Md-EaFrvNb0JypsKL8eWY',
    appId: '1:977368093099:ios:35ee1a1e42a18cb8ec42ee',
    messagingSenderId: '977368093099',
    projectId: 'yesyes-82dcf',
    storageBucket: 'yesyes-82dcf.appspot.com',
    iosBundleId: 'com.example.yesYes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwj3Rfnx3AV7Md-EaFrvNb0JypsKL8eWY',
    appId: '1:977368093099:ios:35ee1a1e42a18cb8ec42ee',
    messagingSenderId: '977368093099',
    projectId: 'yesyes-82dcf',
    storageBucket: 'yesyes-82dcf.appspot.com',
    iosBundleId: 'com.example.yesYes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0DfVCh4ucYp4RMJO2vt6_0N_bTWc858A',
    appId: '1:977368093099:web:23c893e31bd4f79cec42ee',
    messagingSenderId: '977368093099',
    projectId: 'yesyes-82dcf',
    authDomain: 'yesyes-82dcf.firebaseapp.com',
    storageBucket: 'yesyes-82dcf.appspot.com',
    measurementId: 'G-0NX3NHHE5Z',
  );
}
